export const Fonts = {
	black: "jost-black",
	blackitalic: "jost-blackitalic",
	bold: "jost-bold",
	bolditalic: "jost-bolditalic",
	extrabold: "jost-extrabold",
	extrabolditalic: "jost-extrabolditalic",
	extralight: "jost-extralight",
	extralightitalic: "jost-extralightitalic",
	italic: "jost-italic",
	light: "jost-light",
	lightitalic: "jost-lightitalic",
	medium: "jost-medium",
	mediumitalic: "jost-mediumitalic",
	regular: "jost-regular",
	semibold: "jost-semibold",
	semibolditalic: "jost-semibolditalic",
	thin: "jost-thin",
	thinitalic: "jost-thinitalic",
};
